apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - image: nginx:latest
        name: sample-service
        ports:
        - containerPort: 80
